// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ttt_api.proto

package ttt_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TTT struct {
	// Types that are valid to be assigned to Message:
	//	*TTT_Turn
	//	*TTT_End
	//	*TTT_Move
	//	*TTT_PlayerMove
	Message              isTTT_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TTT) Reset()         { *m = TTT{} }
func (m *TTT) String() string { return proto.CompactTextString(m) }
func (*TTT) ProtoMessage()    {}
func (*TTT) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d4350f711106b6, []int{0}
}

func (m *TTT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTT.Unmarshal(m, b)
}
func (m *TTT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTT.Marshal(b, m, deterministic)
}
func (m *TTT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTT.Merge(m, src)
}
func (m *TTT) XXX_Size() int {
	return xxx_messageInfo_TTT.Size(m)
}
func (m *TTT) XXX_DiscardUnknown() {
	xxx_messageInfo_TTT.DiscardUnknown(m)
}

var xxx_messageInfo_TTT proto.InternalMessageInfo

type isTTT_Message interface {
	isTTT_Message()
}

type TTT_Turn struct {
	Turn *Turn `protobuf:"bytes,1,opt,name=turn,proto3,oneof"`
}

type TTT_End struct {
	End *End `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
}

type TTT_Move struct {
	Move *Move `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

type TTT_PlayerMove struct {
	PlayerMove *PlayerMove `protobuf:"bytes,4,opt,name=player_move,json=playerMove,proto3,oneof"`
}

func (*TTT_Turn) isTTT_Message() {}

func (*TTT_End) isTTT_Message() {}

func (*TTT_Move) isTTT_Message() {}

func (*TTT_PlayerMove) isTTT_Message() {}

func (m *TTT) GetMessage() isTTT_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *TTT) GetTurn() *Turn {
	if x, ok := m.GetMessage().(*TTT_Turn); ok {
		return x.Turn
	}
	return nil
}

func (m *TTT) GetEnd() *End {
	if x, ok := m.GetMessage().(*TTT_End); ok {
		return x.End
	}
	return nil
}

func (m *TTT) GetMove() *Move {
	if x, ok := m.GetMessage().(*TTT_Move); ok {
		return x.Move
	}
	return nil
}

func (m *TTT) GetPlayerMove() *PlayerMove {
	if x, ok := m.GetMessage().(*TTT_PlayerMove); ok {
		return x.PlayerMove
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TTT) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TTT_Turn)(nil),
		(*TTT_End)(nil),
		(*TTT_Move)(nil),
		(*TTT_PlayerMove)(nil),
	}
}

type Turn struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeLeft             int64    `protobuf:"varint,2,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	Digit                string   `protobuf:"bytes,3,opt,name=digit,proto3" json:"digit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Turn) Reset()         { *m = Turn{} }
func (m *Turn) String() string { return proto.CompactTextString(m) }
func (*Turn) ProtoMessage()    {}
func (*Turn) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d4350f711106b6, []int{1}
}

func (m *Turn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Turn.Unmarshal(m, b)
}
func (m *Turn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Turn.Marshal(b, m, deterministic)
}
func (m *Turn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Turn.Merge(m, src)
}
func (m *Turn) XXX_Size() int {
	return xxx_messageInfo_Turn.Size(m)
}
func (m *Turn) XXX_DiscardUnknown() {
	xxx_messageInfo_Turn.DiscardUnknown(m)
}

var xxx_messageInfo_Turn proto.InternalMessageInfo

func (m *Turn) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Turn) GetTimeLeft() int64 {
	if m != nil {
		return m.TimeLeft
	}
	return 0
}

func (m *Turn) GetDigit() string {
	if m != nil {
		return m.Digit
	}
	return ""
}

type End struct {
	Winner               string   `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *End) Reset()         { *m = End{} }
func (m *End) String() string { return proto.CompactTextString(m) }
func (*End) ProtoMessage()    {}
func (*End) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d4350f711106b6, []int{2}
}

func (m *End) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_End.Unmarshal(m, b)
}
func (m *End) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_End.Marshal(b, m, deterministic)
}
func (m *End) XXX_Merge(src proto.Message) {
	xxx_messageInfo_End.Merge(m, src)
}
func (m *End) XXX_Size() int {
	return xxx_messageInfo_End.Size(m)
}
func (m *End) XXX_DiscardUnknown() {
	xxx_messageInfo_End.DiscardUnknown(m)
}

var xxx_messageInfo_End proto.InternalMessageInfo

func (m *End) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

type Move struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Digit                string   `protobuf:"bytes,3,opt,name=digit,proto3" json:"digit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d4350f711106b6, []int{3}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Move) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *Move) GetDigit() string {
	if m != nil {
		return m.Digit
	}
	return ""
}

type PlayerMove struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Row                  int32    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	Digit                string   `protobuf:"bytes,4,opt,name=digit,proto3" json:"digit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMove) Reset()         { *m = PlayerMove{} }
func (m *PlayerMove) String() string { return proto.CompactTextString(m) }
func (*PlayerMove) ProtoMessage()    {}
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d4350f711106b6, []int{4}
}

func (m *PlayerMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMove.Unmarshal(m, b)
}
func (m *PlayerMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMove.Marshal(b, m, deterministic)
}
func (m *PlayerMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMove.Merge(m, src)
}
func (m *PlayerMove) XXX_Size() int {
	return xxx_messageInfo_PlayerMove.Size(m)
}
func (m *PlayerMove) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMove.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMove proto.InternalMessageInfo

func (m *PlayerMove) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerMove) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *PlayerMove) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *PlayerMove) GetDigit() string {
	if m != nil {
		return m.Digit
	}
	return ""
}

func init() {
	proto.RegisterType((*TTT)(nil), "ttt_api.TTT")
	proto.RegisterType((*Turn)(nil), "ttt_api.Turn")
	proto.RegisterType((*End)(nil), "ttt_api.End")
	proto.RegisterType((*Move)(nil), "ttt_api.Move")
	proto.RegisterType((*PlayerMove)(nil), "ttt_api.PlayerMove")
}

func init() { proto.RegisterFile("ttt_api.proto", fileDescriptor_25d4350f711106b6) }

var fileDescriptor_25d4350f711106b6 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xd7, 0xa6, 0xdd, 0xfe, 0xbd, 0xfb, 0x4f, 0x24, 0x8a, 0x14, 0x44, 0x18, 0xf5, 0xc5,
	0xa7, 0x3d, 0x28, 0xf8, 0x2c, 0xc2, 0x60, 0x82, 0x82, 0x84, 0xe2, 0x6b, 0xa9, 0x26, 0x1b, 0x81,
	0x36, 0x29, 0x59, 0xb6, 0xe1, 0xf7, 0xf2, 0x03, 0xca, 0xbd, 0xc6, 0x2a, 0x4e, 0xdf, 0xee, 0xb9,
	0xe7, 0xf4, 0x77, 0x4f, 0x09, 0x4c, 0xbc, 0xf7, 0x55, 0xdd, 0xe9, 0x59, 0xe7, 0xac, 0xb7, 0x7c,
	0x14, 0x64, 0xf1, 0x16, 0x01, 0x2b, 0xcb, 0x92, 0x9f, 0x43, 0xe2, 0x37, 0xce, 0xe4, 0xd1, 0x34,
	0xba, 0x18, 0x5f, 0x4e, 0x66, 0x9f, 0xf1, 0x72, 0xe3, 0xcc, 0x62, 0x20, 0xc8, 0xe4, 0x53, 0x60,
	0xca, 0xc8, 0x3c, 0xa6, 0xcc, 0xff, 0x3e, 0x33, 0x37, 0x72, 0x31, 0x10, 0x68, 0x21, 0xa6, 0xb5,
	0x5b, 0x95, 0xb3, 0x1f, 0x98, 0x07, 0xbb, 0x55, 0x88, 0x41, 0x93, 0x5f, 0xc3, 0xb8, 0x6b, 0xea,
	0x57, 0xe5, 0x2a, 0xca, 0x26, 0x94, 0x3d, 0xea, 0xb3, 0x8f, 0xe4, 0x85, 0x2f, 0xa0, 0xeb, 0xd5,
	0x6d, 0x06, 0xa3, 0x56, 0xad, 0xd7, 0xf5, 0x4a, 0x15, 0x77, 0x90, 0x60, 0x33, 0x7e, 0x00, 0xb1,
	0x96, 0x54, 0x3a, 0x13, 0xb1, 0x96, 0xfc, 0x14, 0x32, 0xaf, 0x5b, 0x55, 0x35, 0x6a, 0xe9, 0xa9,
	0x27, 0x13, 0xff, 0x70, 0x71, 0xaf, 0x96, 0x9e, 0x1f, 0x43, 0x2a, 0xf5, 0x4a, 0x7b, 0x6a, 0x97,
	0x89, 0x0f, 0x51, 0x9c, 0x01, 0x9b, 0x1b, 0xc9, 0x4f, 0x60, 0xb8, 0xd3, 0xc6, 0x28, 0x17, 0x68,
	0x41, 0x15, 0x37, 0x90, 0xe0, 0x71, 0x7e, 0x08, 0xcc, 0xd9, 0x1d, 0x99, 0xa9, 0xc0, 0x11, 0x37,
	0x2f, 0xb6, 0xa1, 0x2b, 0xa9, 0xc0, 0xf1, 0x8f, 0x03, 0x4f, 0x00, 0x5f, 0xbf, 0xb4, 0xd7, 0x38,
	0x70, 0xe3, 0x3d, 0x2e, 0xfb, 0x85, 0x9b, 0x7c, 0xe3, 0x3e, 0x0f, 0xe9, 0x29, 0xaf, 0xde, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x41, 0x3f, 0x02, 0x45, 0xdb, 0x01, 0x00, 0x00,
}
